### ISSUE TITLE
it's really hard to use this package to connect to more than one cluster

### ISSUE THREAD

**Issue by tpihl** [nats-io/jsm.go#6]
Since all settings are global to the package, the only way to use this package while connecting to two clusters would be by importing it twice and duplicate all code referring to each instance.

Could this be made simpler?

**Comment by ripienaar** [comment]
Yes, for some background, we have no idea how jsm will look when done, parts of it will go into nats.go and parts in here - parts might even go away.

So when I wrote this I made it primarily for the `nats` utility knowing I'll need to do some big refactors down the line once we know what we actually need.

I can probably make it a bit easier for you now but its quite a change, worth doing anyway so I'll get into that

**Comment by ripienaar** [comment]
I've made https://github.com/nats-io/jsm.go/pull/7 I am not quite ready with it so will think about a few things more....but this adds connection options, contextes, timeouts all the things to all the places.

Has an unfortunate increase in verbosity - for the moment the `SetConnection()` is still there and will be used as default unless you specify it otherwise, I might retrain these methods but maybe make give them names reflecting their new behaviour as default configs unless otherwise configured.

So now you do something like:

```go
nc, _ := nats.Connect(servers)
str, _ := jsm.NewStream("S", jsm.FileStorage(), jsm.StreamConnection(jsm.WithConnection(nc)))
```

if `SetConnection(nc)` was called before the `jsm.StreamConnection()` would be not needed. 

Later if you make a new Consumer:

```go
c, _ := str.NewConsumerFromDefault(jsm.SampledDefaultConsumer, jsm.DurableName("q1"))
```

You don't need to specify the connection again it will take from the stream, however if you do specify it that will be used.

other things like `jsm.IsJetStreamEnabled(jjsm.WithTimeout(time.Second))` is also now supported.

Like I said I'll have a think about some other approaches but this was the first thing, the way I made this package around the server config strucutures isnt optimal so this also changes things around a bit so later once JetStream stablise I can drop the server dependency easier.

**Comment by ripienaar** [comment]
I should add I think existing code will basically keep working until I change things like `jsm.SetConnection()`

**Comment by tpihl** [comment]
Very nice. My code continued to work without change, will try out the new features tomorrow, cheers!

**Comment by tpihl** [comment]
Couldn't help myself. Works great. And the WithContext makes the logic alot simpler for pull.

This is quite good enough API for my current tests (so i will find new tests :))
This issue can be closed from my perspective

/T

**Comment by tpihl** [comment]
Maybe wait to close until it's merged? sry :)

**Comment by ripienaar** [comment]
Merged this, also fixed `NextMsgs()`, I might tweak things a bit more after some real life use but its for sure an improvement
